name: altoproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Gestion d'état
  flutter_riverpod: ^2.5.1
  riverpod: ^2.6.1
  provider: ^6.1.2

  # QR Code & Scan
  mobile_scanner: ^5.2.3
  qr_flutter: ^4.1.0

  # Cryptographie & Sécurité
  pointycastle: ^3.9.1
  basic_utils: ^5.7.0
  flutter_secure_storage: ^9.2.2

  # Stockage local
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4

  # Réseau & API
  http: ^1.2.2

  # Utilitaires
  uuid: ^4.5.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
